# Generated by Django 5.2.7 on 2026-03-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_expand_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='matchnotification',
            new_name='matches_mat_recipie_8cf449_idx',
            old_name='matches_mat_recipie_ff9374_idx',
        ),
        migrations.RenameIndex(
            model_name='matchnotification',
            new_name='matches_mat_recipie_33ff58_idx',
            old_name='matches_mat_recipie_2b7f84_idx',
        ),
        migrations.RenameIndex(
            model_name='matchnotification',
            new_name='matches_mat_created_86d59c_idx',
            old_name='matches_mat_created_80ee14_idx',
        ),
    ]
